language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm install
script:
  - git clone https://github.com/renefritze/22__RSE__DAY
  - cd 22__RSE__DAY
  - npm install
  - npm run html
  - npm run pdf
